### ISSUE TITLE
What is the point of this action?

### ISSUE THREAD

**Issue by Sorebit** [rehanhaider/pelican-to-github-pages#2]
What exactly is the point of this action?
Please consider `make github` has the exact same functionality, is arguably faster and doesn't need any server time.

**Comment by rehanhaider** [comment]
Yes you can. But if you're collaborating with several developers / writers and want to make sure they're not breaking your website that is when you need to run CI / CD and use this kind of an action. 

But if `make github` suits your purposes, feel free to use it.

**Comment by egberts** [comment]
now we can edit Markdown files from our iPad and click SUBMIT,  presto, new website.
