### ISSUE TITLE
npm run build when theme folder

### ISSUE THREAD

**Issue by sonic182** [rehanhaider/pelican-to-github-pages#3]
It may be good to have `npm run build` when building theme node-dependencies? for stuffs like webpack, tailwind, ... etc

**Comment by rehanhaider** [comment]
Do you want to make the changes and submit a PR?

**Comment by jkw** [comment]
> It may be good to have `npm run build` when building theme node-dependencies? for stuffs like webpack, tailwind, ... etc

The theme should already be "Pelican Ready", no need for JavaScript mumbojumbo on deployment. This tool is for publishing your page trough Pelican to Github Pages. Not to do theme generating.

**Comment by sonic182** [comment]
> > It may be good to have `npm run build` when building theme node-dependencies? for stuffs like webpack, tailwind, ... etc
> 
> The theme should already be "Pelican Ready", no need for JavaScript mumbojumbo on deployment. This tool is for publishing your page trough Pelican to Github Pages. Not to do theme generating.

I realized that, for some custom made stuffs, we can just use the Makefile

**Comment by rehanhaider** [comment]
> > It may be good to have `npm run build` when building theme node-dependencies? for stuffs like webpack, tailwind, ... etc
> 
> The theme should already be "Pelican Ready", no need for JavaScript mumbojumbo on deployment. This tool is for publishing your page trough Pelican to Github Pages. Not to do theme generating.

The only drawback is, which I still haven't solved yet but will have to find a workaround before CloudBytes Dev Academy is launched, is how to integrate tailwinds in the dev process. 

The fact of the matter is Python WebDev tools aren't mature enough and beyond a point not a marketable skill unless the dev learns JS frameworks. 

So while I agree, themes should be Pelican Ready and the objective of this action is purely deployment, it won't hurt for us to solve how to build seamlessly without resorting to manual steps.

**Comment by rehanhaider** [comment]
Do you want to make the changes and submit a PR?

**Comment by sonic182** [comment]
sorry, I did use a Makefile with all required stuffs, without using this action
